name = "aaa_texts"
description = "Utilities to deal with enriched human texts (ANSI, Unicode)"
version = "0.1.0-dev"

authors = ["Alejandro R. Mosteo"]
maintainers = ["Alejandro R. Mosteo <alejandro@mosteo.com>"]
maintainers-logins = ["mosteo"]
licenses = "LGPL-3.0-only"
website = ""
tags = ["unicode", "ansi", "console", "terminal", "tables"]

[[depends-on]]
aaa     = "~0.3.0"
ansiada = "^1.1.0"
lml     = "~0.1.0"
umwi    = "~0.1.0"

[[pins]]
aaa = { path="../aaa_base" }

# lml = { path="../../lml_ada" }
lml = { url="https://github.com/mosteo/lml_ada", branch="feat/yeison" }

# umwi = { url="https://github.com/mosteo/umwi", branch="main" }

[[actions]]
type = "test"
directory = "test"
command = ["alr", "run"]